### ISSUE TITLE
Missing core files

### ISSUE THREAD

**Issue by ghost** [TechFish3000/Techfish-Orbital#1]
When I download and install the mod error came
![20191031_142900](https://user-images.githubusercontent.com/53652646/67932930-d53d6380-fbea-11e9-8ed3-651679ecbbe1.jpg)

**Comment by ignyx** [comment]
You need to install the [techfish-core mod](https://github.com/TechFish3000/Techfish-Core). However I do agree that this dependency should be indicated in the readme.

**Comment by TechFish3000** [comment]
Ok, will do
