### ISSUE TITLE
Possible update or texture fix

### ISSUE THREAD

**Issue by Spartanq** [TechFish3000/Techfish-Orbital#3]
Many of the items and buildings don't have textures, or aren't implemented. I like what I see so far, and no weapons

**Comment by TechFish3000** [comment]
I've kinda stopped work on the mod for now, don't expect updates for 1-2 months. I'm currently working on personal projects and such. And there's the fact I'm terrible at graphic design.

**Comment by Spartanq** [comment]
It's ok, I was just letting you know, and thanks for the mod, it's very
cool, but kind of confusing, thank you nontheless.
